{% set name = "jupyterclearcheck" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/jupyterclearcheck-{{ version }}.tar.gz
  sha256: 68e0fd81e6aa17ef01ddc42f27365101ef3e70812a41d5154f994dc21a14c6f4

build:
  entry_points:
    - jupyterclearcheck = jupyterclearcheck.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - pdm-backend
    - pip
  run:
    - python >=3.9
    - nbformat >=5.10.4

test:
  imports:
    - jupyterclearcheck
  commands:
    - pip check
    - jupyterclearcheck --help
  requires:
    - pip

about:
  summary: A Python CLI to check that a Jupyter Notebook's Outputs' have been cleared.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - guru-desh
