name: Publish to PyPI on Tag

on:
  push:
    tags:
      - "v*"

jobs:
  pypi-publish:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pdm install --prod

      - name: Build and Publish to PyPI
        run: |
          pdm publish --repository testpypi
