name: Publish to PyPI on Tag

on:
  push:
    tags:
      - "v*.*.*"
    branches:
      - test-cd

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up PDM
        uses: pdm-project/setup-pdm@v
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pdm install --prod

      - name: Build and Publish to PyPI
        env:
          PDM_PUBLISH_USERNAME: ${{ secrets.PDM_PUBLISH_USERNAME }}
          PDM_PUBLISH_PASSWORD: ${{ secrets.PDM_PUBLISH_PASSWORD }}
        run: |
          pdm publish --repository testpypi
