name: Bump version and Create PR with version tag

on:
  workflow_dispatch:
    inputs:
      bump-type:
        description: "Bump type"
        required: true
        default: "patch"
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  bump:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pdm install

      - name: Configure Git
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"

      - name: Bump version and create tag
        run: |
          pdm run bump-version ${{ github.event.inputs['bump-type'] }} --commit --tag

      - name: Push changes to branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin HEAD:bump-version-${{ github.event.inputs['bump-type'] }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Bump version to {new_version}"
          branch: "bump-version-${{ github.event.inputs['bump-type'] }}"
          base: main
          title: "Bump version to {new_version}"
          body: "This PR bumps the version to {new_version}."
          labels: "automated PR"
